# Generated by Django 2.0 on 2017-12-05 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20171205_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitem',
            name='notes',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Note'),
        ),
    ]
