# Generated by Django 2.0 on 2017-12-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_auto_20171205_0750"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entityresource",
            name="data",
            field=models.CharField(max_length=255),
        ),
    ]
