# Generated by Django 2.0 on 2017-12-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_auto_20171208_1300"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name="entity",
            name="rating",
            field=models.IntegerField(blank=True, default=None, max_length=1),
        ),
        migrations.AddField(
            model_name="entity",
            name="tags",
            field=models.ManyToManyField(related_name="tags", to="catalog.Tag"),
        ),
    ]
